name-template: 'kubedock-$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
exclude-labels:
  - 'skip-changelog'
categories:
  - title: 'ğŸ’¥ BREAKING CHANGES'
    labels:
      - 'breaking'
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ğŸ§° Maintenance'
    labels:
      - 'chore'
      - 'documentation'
      - 'ci'
      - 'refactor'
      - 'style'
      - 'test'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'refactor'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'documentation'
      - 'ci'
      - 'style'
      - 'test'
  default: patch
autolabeler:
  - label: 'breaking'
    title:
      - '/!:/'
    body:
      - '/BREAKING CHANGE/'
  - label: 'chore'
    title:
      - '/^chore(\(.*\))?!?:/i'
  - label: 'ci'
    title:
      - '/^(ci|build)(\(.*\))?!?:/i'
    files:
      - '.github/*'
      - '.github/**/*'
  - label: 'documentation'
    title:
      - '/^docs(\(.*\))?!?:/i'
    files:
      - '*.md'
      - '**/*.md'
  - label: 'enhancement'
    title:
      - '/^(feat|perf)(\(.*\))?!?:/i'
  - label: 'bug'
    title:
      - '/^(fix|hotfix|bug)(\(.*\))?!?:/i'
  - label: 'refactor'
    title:
      - '/^refactor(\(.*\))?!?:/i'
  - label: 'revert'
    title:
      - '/^revert(\(.*\))?!?:/i'
  - label: 'style'
    title:
      - '/^style(\(.*\))?!?:/i'
  - label: 'test'
    title:
      - '/^test(\(.*\))?!?:/i'
template: |
  ## Changes

  $CHANGES